local p = require("vagari.palette")
local links = {}

-- 🧩 syntax {{{

links.syntax = {
	Comment = { fg = p.slt_2 },
	Constant = { fg = p.orn_1 },
	String = { fg = p.grn_4 },
	Character = { fg = p.grn_2 },
	Number = { fg = p.pnk_3 },
	Boolean = { fg = p.cyn_3 },
	Float = { fg = p.pnk_4 },
	Identifier = { fg = p.asn_3 },
	Function = { fg = p.orn_3 },
	Statement = { fg = p.prp_4 },
	Conditional = { fg = p.prp_2 },
	Repeat = { fg = p.prp_3 },
	Label = { fg = p.asn_3 },
	Operator = { fg = p.cyn_4 },
	Keyword = { fg = p.prp_4 },
	Exception = { fg = p.prp_2 },
	PreProc = { fg = p.blu_4 },
	Include = { fg = p.blu_3 },
	Define = { fg = p.blu_2 },
	Macro = { fg = p.blu_2 },
	PreCondit = { fg = p.blu_1 },
	Type = { fg = p.sun_4 },
	StorageClass = { fg = p.sun_3 },
	Structure = { fg = p.sun_2 },
	Typedef = { fg = p.sun_3 },
	Special = { fg = p.sky_4 },
	SpecialChar = { fg = p.sky_2 },
	Title = { fg = p.sky_4 },
	Tag = { fg = p.sky_3 },
	Delimiter = { fg = p.sky_2 },
	SpecialComment = { fg = p.sky_0 },
	Debug = { fg = p.sky_1 },
	Underlined = { fg = p.tyr_3 },
	Ignore = { fg = p.gry_2 },
	Error = { fg = p.rby_3 },
	Todo = { fg = p.orn_4 },
}

-- }}}

-- 📚 lsp {{{

links.lsp = {
	Default = {},
	Array = {},
	Boolean = {},
	Class = {},
	Color = {},
	Constant = {},
	Constructor = {},
	Enum = {},
	EnumMember = {},
	Event = {},
	Field = {},
	File = {},
	Folder = {},
	Function = {},
	Interface = {},
	Key = {},
	Keyword = {},
	Method = {},
	Module = {},
	Namespace = {},
	Null = {},
	Number = {},
	Object = {},
	Operator = {},
	Package = {},
	Property = {},
	Reference = {},
	Snippet = {},
	String = {},
	Struct = {},
	Text = {},
	TypeParameter = {},
	Unit = {},
	Value = {},
	Variable = {},
}

-- }}}

-- 👀 ui {{{

links.ui = {
    -- Error = {},
    -- Success = {},
    -- Warning = {},
    -- Important = {},
    -- Critical = {},
    -- Continuous = {},
    -- Inner = {},
    -- Outer = {},
    -- Border = {},
    -- Broken = {},
    -- Locked = {},
    -- Hidden = {},
    -- Faint = { p.drk_0 },
    -- Min = {},
    -- Minor = {},
    -- Normal = {},
    -- Major = {},
    -- Max = {},
    -- Positive = {},
    -- Negative = {},
    -- Neutral = {},
    -- Fold = {},
    -- h1 = {},
    -- h2 = {},
    -- h3 = {},
    -- h4 = {},
    -- h5 = {},
    -- h6 = {},
    -- Occupied = {},
    -- Empty = {},
    -- Inactive = {},
    -- Active = {},
    -- Visited = {},
    -- Internal = {},
    -- Exterenal = {},
    -- Images = {},
    -- Video = {},
    -- Loading = {},
    -- Paused = {},
    -- Start = {},
    -- End = {},
    -- Match = {},
    -- Highilight = {},
    -- Selection = {},
    -- Selected = {},
    -- New = {},
    -- Modified = {},
    -- Delete = {},
    -- Add = {},
}

-- }}}

return links
